/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesCrmRouteImport } from './routes/sales-crm'
import { Route as SalesSupportManagerRouteImport } from './routes/sales-support-manager'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SupportAgentRouteImport } from './routes/support-agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCrmRoute = SalesCrmRouteImport.update({
  id: '/sales-crm',
  path: '/sales-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSupportManagerRoute = SalesSupportManagerRouteImport.update({
  id: '/sales-support-manager',
  path: '/sales-support-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportAgentRoute = SupportAgentRouteImport.update({
  id: '/support-agent',
  path: '/support-agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sales-crm': typeof SalesCrmRoute
  '/sales-support-manager': typeof SalesSupportManagerRoute
  '/support': typeof SupportRoute
  '/support-agent': typeof SupportAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sales-crm': typeof SalesCrmRoute
  '/sales-support-manager': typeof SalesSupportManagerRoute
  '/support': typeof SupportRoute
  '/support-agent': typeof SupportAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sales-crm': typeof SalesCrmRoute
  '/sales-support-manager': typeof SalesSupportManagerRoute
  '/support': typeof SupportRoute
  '/support-agent': typeof SupportAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sales-crm'
    | '/sales-support-manager'
    | '/support'
    | '/support-agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sales-crm'
    | '/sales-support-manager'
    | '/support'
    | '/support-agent'
  id:
    | '__root__'
    | '/'
    | '/sales-crm'
    | '/sales-support-manager'
    | '/support'
    | '/support-agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalesCrmRoute: typeof SalesCrmRoute
  SalesSupportManagerRoute: typeof SalesSupportManagerRoute
  SupportRoute: typeof SupportRoute
  SupportAgentRoute: typeof SupportAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-crm': {
      id: '/sales-crm'
      path: '/sales-crm'
      fullPath: '/sales-crm'
      preLoaderRoute: typeof SalesCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-support-manager': {
      id: '/sales-support-manager'
      path: '/sales-support-manager'
      fullPath: '/sales-support-manager'
      preLoaderRoute: typeof SalesSupportManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-agent': {
      id: '/support-agent'
      path: '/support-agent'
      fullPath: '/support-agent'
      preLoaderRoute: typeof SupportAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalesCrmRoute: SalesCrmRoute,
  SalesSupportManagerRoute: SalesSupportManagerRoute,
  SupportRoute: SupportRoute,
  SupportAgentRoute: SupportAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
